# -*- coding: utf-8 -*-
"""
BCRF File Handler Utility Module

This module provides utilities for reading and processing BCRF files from
SPM (Scanning Probe Microscopy) images generated by Bruker devices.

Functions:
    read_bcrf_file: Read BCRF file and extract header and raw data
    convert_data_to_float: Convert binary data to float array
    load_bcrf_image: Load complete BCRF image as numpy array with metadata
"""

import numpy as np
import struct
from typing import Tuple, Dict, Optional


# Default BCRF file specifications
DEFAULT_HEADER_SIZE = 4096  # bytes
DEFAULT_IMAGE_WIDTH = 256  # pixels
DEFAULT_IMAGE_HEIGHT = 256  # pixels
DEFAULT_DATA_TYPE = np.float32  # 32-bit floating point


def read_bcrf_file(
    filename: str,
    header_size: int = DEFAULT_HEADER_SIZE,
    width: int = DEFAULT_IMAGE_WIDTH,
    height: int = DEFAULT_IMAGE_HEIGHT,
) -> Tuple[Dict[str, str], bytes]:
    """
    Read BCRF file and extract header metadata and raw image data.

    Args:
        filename: Path to the BCRF file
        header_size: Size of header in bytes (default: 4096)
        width: Image width in pixels (default: 256)
        height: Image height in pixels (default: 256)

    Returns:
        Tuple containing:
            - header_dict: Dictionary with parsed header key-value pairs
            - data: Raw binary image data

    Raises:
        FileNotFoundError: If file does not exist
        IOError: If file cannot be read
    """
    data_size = width * height * 4  # 32-bit float = 4 bytes per pixel

    try:
        with open(filename, "rb") as file:
            # Read the header
            header = file.read(header_size)

            # Parse the header values (UTF-16 encoded)
            header_dict = {}
            try:
                decoded_header = header.decode("utf-16").replace("\x00", "")
                for line in decoded_header.split("\n"):
                    if "=" in line:
                        key, value = line.strip().split("=", 1)
                        header_dict[key.strip()] = value.strip()
            except UnicodeDecodeError:
                # Fallback to UTF-8 if UTF-16 fails
                decoded_header = header.decode("utf-8", errors="ignore").replace("\x00", "")
                for line in decoded_header.split("\n"):
                    if "=" in line:
                        key, value = line.strip().split("=", 1)
                        header_dict[key.strip()] = value.strip()

            # Read the image data
            data = file.read(data_size)

            if len(data) < data_size:
                raise IOError(
                    f"Unexpected file size. Expected at least {data_size} bytes, "
                    f"got {len(data)} bytes"
                )

    except FileNotFoundError:
        raise FileNotFoundError(f"BCRF file not found: {filename}")
    except Exception as e:
        raise IOError(f"Error reading BCRF file: {str(e)}")

    return header_dict, data


def convert_data_to_float(
    data: bytes, dtype: type = np.float32
) -> np.ndarray:
    """
    Convert binary data to float array.

    Args:
        data: Raw binary image data
        dtype: NumPy data type for conversion (default: np.float32)

    Returns:
        1D numpy array of float values

    Raises:
        ValueError: If data cannot be converted to float
    """
    if dtype == np.float32:
        format_char = "f"
    elif dtype == np.float64:
        format_char = "d"
    else:
        raise ValueError(f"Unsupported data type: {dtype}")

    try:
        num_values = len(data) // struct.calcsize(format_char)
        float_data = struct.unpack("<" + format_char * num_values, data[:num_values * struct.calcsize(format_char)])
        return np.array(float_data, dtype=dtype)
    except struct.error as e:
        raise ValueError(f"Error converting data to float: {str(e)}")


def load_bcrf_image(
    filename: str,
    width: int = DEFAULT_IMAGE_WIDTH,
    height: int = DEFAULT_IMAGE_HEIGHT,
) -> Tuple[np.ndarray, Dict[str, str]]:
    """
    Load complete BCRF image as a 2D numpy array with metadata.

    Args:
        filename: Path to the BCRF file
        width: Image width in pixels (default: 256)
        height: Image height in pixels (default: 256)

    Returns:
        Tuple containing:
            - image: 2D numpy array of shape (height, width)
            - metadata: Dictionary with header information

    Raises:
        FileNotFoundError: If file does not exist
        IOError: If file cannot be read or reshaped
    """
    header_dict, data = read_bcrf_file(filename, width=width, height=height)

    try:
        float_data = convert_data_to_float(data)
        image = float_data.reshape((height, width))
    except ValueError as e:
        raise IOError(f"Error reshaping image data: {str(e)}")

    return image, header_dict


def get_image_statistics(image: np.ndarray) -> Dict[str, float]:
    """
    Calculate statistics for an image array.

    Args:
        image: 2D numpy array

    Returns:
        Dictionary with min, max, mean, and std values
    """
    return {
        "min": float(np.min(image)),
        "max": float(np.max(image)),
        "mean": float(np.mean(image)),
        "std": float(np.std(image)),
    }
